= io.teak.sdk.Teak.AttributedLaunchData
:caution-caption: Deprecated

Base class for describing a Teak-attributed launch of the app.

== Attributes

=== scheduleName


The name of the schedule responsible on the Teak dashboard; or null if this was not a scheduled channel.

=== scheduleId


The id of the schedule responsible on the Teak dashboard; or null if this was not a scheduled channel.

=== creativeName


The name of the creative on the Teak dashboard.

=== creativeId


The id of the creative on the Teak dashboard.

=== rewardId


The id of the Teak reward associated with this launch; or null.

=== channelName


The name of the channel responsible for this attribution.

=== deepLink


The deep link associated with this launch; or null.

== Methods

=== mergeDeepLink

[object Object]

[source,csharp]
----
AttributedLaunchData mergeDeepLink(@NonNull Uri uri);
----
// TODO: collapseable here?

[cols="1,2a"]
|===
|Parameter |Description

|uri |
|===

=== isIncentivized



[source,csharp]
----
boolean isIncentivized();
----
// TODO: collapseable here?


=== toSessionAttributionMap



[source,csharp]
----
Map undefined toSessionAttributionMap();
----
// TODO: collapseable here?


=== toMap

Convert to a Map, intended to be converted to JSON and consumed by the Teak Unity SDK.

[source,csharp]
----
Map undefined toMap();
----
// TODO: collapseable here?



